dataset:
    name: cifar10
    batch_size: 128

model:
    name: cnn
    cnn: [32, M , 32, A, 64, A]
    fc: [1024, 64, 10]
    num_epochs: 5

optimizer:
    num_epochs: 1
    name: SimplifiedHessian

loss:
    name: CrossEntropy

metrics:
    names: [accuracy]