dataset:
    name: mnist
    batch_size: 128

model:
    name: mlp
    layers_size: [784, 800, 10]
    num_epochs: 5

optimizer:
    num_epochs: 3
    name: Adam
    lr: 0.001
    weight_decay: 0.00001

loss:
    name: CrossEntropy

metrics:
    names: [accuracy]