dataset:
    name: cifar10
    batch_size: 128

model:
    name: resnet18
    num_classes: 10

optimizer:
    num_epochs: 10
    name: Adam
    lr: 0.001

loss:
    name: CrossEntropy

metrics:
    names: [accuracy]