dataset:
    name: cifar10
    batch_size: 128

model:
    name: resnet18
    num_classes: 10

optimizer:
    num_epochs: 20
    name: SGD
    lr: 0.01

loss:
    name: CrossEntropy

metrics:
    names: [accuracy]