dataset:
    name: cifar10
    batch_size: 128

model:
    name: cnn
    cnn: [32, M , 32, A, 64, A]
    fc: [1024, 64, 10]

optimizer:
    num_epochs: 10
    name: Adam
    lr: 0.001

loss:
    name: CrossEntropy

metrics:
    names: [accuracy]