dataset:
    name: mnist
    batch_size: 128

model:
    name: mlp
    fc: [784, 128, 64, 32, 10]
    batch_norm: True

optimizer:
    num_epochs: 10
    name: SGD
    lr: 0.01

loss:
    name: CrossEntropy

metrics:
    names: [accuracy]